# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mblog', '0002_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topicId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mblog.Topic'),
        ),
    ]
